CREATE TABLE tramite (
    id                    NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_id               NUMBER(19)     NOT NULL,
    vecino_username       VARCHAR2(150)  NOT NULL,
    descripcion           VARCHAR2(500)  NOT NULL,
    direccion             VARCHAR2(300),
    estado                VARCHAR2(20)   DEFAULT 'INGRESADO' NOT NULL,
    funcionario_asignado  VARCHAR2(150),
    cuadrilla_asignada    VARCHAR2(150),
    fecha_ingreso         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_admision        TIMESTAMP,
    fecha_resolucion      TIMESTAMP
);

CREATE INDEX idx_tramite_tipo_admision ON tramite (tipo_id, fecha_admision);
CREATE INDEX idx_tramite_vecino ON tramite (vecino_username);
